# Development configuration file for the Eufy Security Siren Integration application.

General:
  AppName: eufy-siren
  PollingInterval: 10

Files:
  LogfileName: logs/logfile.log
  LogfileMaxLines: 10000
  LogProcessID: False
  LogfileVerbosity: debug
  ConsoleVerbosity: debug

Email:
  EnableEmail: True
  SubjectPrefix: "[Dev eufy-siren]: "

SCSmartDevices:
  AllowDebugLogging: False
  SimulationFileFolder: simulation_files/
  Devices:
    - Name: Spello Siren
      Model: Shelly2PMG3
      Hostname: 192.168.86.36
      Simulate: False
      ExpectOffline: True
      Outputs:
        - Name: "Spello Siren O1"
        - Name: "Spello Siren O2"

ServiceAPI:
  Enable: True
  HostingIP: 0.0.0.0
  Port: 8085
  Endpoints:
    - Name: "Camera 1"
      URL: "/motion/camera1"
      Action: "Motion"
    - Name: "Camera 2"
      URL: "/motion/camera2"
      Action: "Motion"
    - Name: "Camera 3"
      URL: "/motion/camera3"
      Action: "Motion"
    - Name: "Camera 4"
      URL: "/motion/camera4"
      Action: "Ignore"
    - Name: "Start Siren"
      URL: "/siren/start"
      Action: "StartSiren"
    - Name: "Stop Siren"
      URL: "/siren/stop"
      Action: "StopSiren"

Siren:
  Enable: True
  Switch: "Spello Siren O1"
  SirenDuration: 30
  MinMotionEvents: 2
  MinMotionSources: 2
  MinMotionInterval: 10
  MaxMotionInterval: 60
  PostTriggerSleepTimer: 60

HeartbeatMonitor:
  Enable: True
  WebsiteURL: https://uptime.betterstack.com/api/v1/heartbeat/g93Vsb4YEqiScCuzUtMzXzhP
  HeartbeatTimeout: 5